# .github/workflows/docker-build.yml
#adding comment
#adding comment #4
#adding comment for final pull request
name: Docker Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jt1975sc/hellohttp-app:${{ github.sha }} .
          docker images

      - name: Push Docker image
        run: |
          docker push jt1975sc/hellohttp-app:${{ github.sha }}

